import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:minha_livraria/model/AutoGenerated.dart';

class ViewPage extends StatefulWidget {
  VolumeInfo volumeInfo;
  ViewPage({@required this.volumeInfo});
  @override
  _ViewPageState createState() => _ViewPageState();
}

class _ViewPageState extends State<ViewPage> {
  @override
  Widget build(BuildContext context) {
    VolumeInfo _vol = widget.volumeInfo;
    return Scaffold(
      backgroundColor: Colors.blueGrey[50],
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.black,),
          onPressed: (){
            Navigator.pop(context);
          },
        ),
        backgroundColor: Colors.white,
        elevation: 3,
        title: Text(_vol.title, style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: Container(
        padding: EdgeInsets.all(20),
        width: double.maxFinite,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            
            Container(
              padding: const EdgeInsets.all(8.0),
              child: Image.network(_vol.imageLinks.thumbnail),
            ),

            Card(
              child: Padding(
                padding: const EdgeInsets.all(10),
                child: ListTile(
                  title: Text(_vol.title, textAlign: TextAlign.justify),
                  subtitle: Text(_vol.description, textAlign: TextAlign.justify),
                ),
              ),
            ),

          ],
        ),
      ),
    );
  }
}