import 'dart:convert';

import 'package:minha_livraria/model/AutoGenerated.dart';
import 'package:http/http.dart' as http;

class Api {
  String baseUrl = "https://www.googleapis.com/books/v1/volumes?q=";

  Future<List<Items>> search(String search) async {
    String url = baseUrl + search;
    var response = await http.get(url); 
    if (response.statusCode >= 200 && response.statusCode < 300) {
      return Autogenerated.fromJson(jsonDecode(response.body)).items;
    } else{
      print(jsonDecode(response.body));
      return [];
    }
  }
  
}